---
title: "Modelos Lineales"
---


```{r, eval=FALSE, echo=FALSE}
#knit: (function(input_file, encoding) {
#  out_dir <- 'docs';
#  rmarkdown::render(input_file,
# encoding=encoding,
# output_file=file.path(dirname(input_file), out_dir, 'mlineales.html'))})
```

Seguimos usando la data del artículo:

Holland, Alisha C., and José Incio. 2018. “Imperfect Recall: The Politics of Subnational Office Removals.” Comparative Political Studies: 0010414018797939.

```{r}
library(rio)
recall<-import("https://github.com/jincio/Imperfect_recall/raw/master/recalldataset.dta")
```

## Modelo Lineal 

```{r}
m1<-lm(enp~indigenous+execution, data=recall)
summary(m1)
```

```{r}
m1<-lm(enp~indigenous+execution*incumbent, data=recall)
summary(m1)
```

## Robust Estandard Errors


```{r}
library(lmtest)
library(sandwich)
coeftest(m1, vcov = vcovHC(m1, "HC0")) 
```

## Diagnostico

### Valores influyentes 

```{r}
library(car)
qqPlot(m1)
```

```{r}
outlierTest(m1) 
```

```{r}

```

### Multicolinealidad

```{r}
vif(m1)
sqrt(vif(m1)) > 2 
```

### Normalidad de los residuos 

```{r}
res<-residuals(m1)
```

```{r}
library(nortest)
sf.test(res)
ad.test(res)
```

### Homocedasticidad

```{r}
fit<-fitted.values(m1)
scatterplot(fit,res)
```

```{r}
spreadLevelPlot(m1)
```

```{r}
library(lmtest)
bptest(m1)
```

